# Generated by Django 5.0.6 on 2024-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id_gato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=100)),
                ('esterilizado', models.BooleanField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
